In [1]:
import numpy as np

In [3]:
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr1d

array([1, 2, 3, 4, 5, 6])

In [4]:
arr1d + 10

array([11, 12, 13, 14, 15, 16])

In [6]:
arr1d - 2

array([-1,  0,  1,  2,  3,  4])

In [9]:
arr1d >= 4

array([False, False, False,  True,  True,  True])

In [11]:
arr2d = np.arange(12).reshape(2, 6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
arr1d + arr2d

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17]])

In [14]:
arr = np.arange(10, 12).reshape(2, 1)
arr

array([[10],
       [11]])

In [15]:
arr * arr2d

array([[  0,  10,  20,  30,  40,  50],
       [ 66,  77,  88,  99, 110, 121]])

In [17]:
arr_1 = np.arange(12).reshape(4, 3)
arr_2 = np.arange(12).reshape(3, 4)
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr[1]

array([4, 5, 6])

In [32]:
arr[0,2]

np.int64(3)

In [33]:
arr[0][2]

np.int64(3)

In [39]:
arr[:,:2]

array([[1, 2],
       [4, 5]])

In [40]:
arr[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [46]:
arr1 = np.random.randint(1,9,9).reshape(3,3)
arr1

array([[4, 1, 3],
       [8, 3, 2],
       [2, 2, 7]], dtype=int32)

In [55]:
i_row = [0,1,2]
i_col = [0,1,2]

In [59]:
arr1[i_row,i_col]

array([4, 3, 7], dtype=int32)

In [63]:
arr2 = np.array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
arr3 = np.array([
      [[4, 1, 3],
       [8, 3, 2],
       [2, 2, 7]], 
    
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]

])

In [71]:
i_matrix = [0,0,0,1,1,1]
i_row = [0,1,2,0,1,2]
i_col = [0,1,2,0,1,2]

In [72]:
arr3[i_matrix, i_row, i_col]

array([ 4,  3,  7, 10, 50, 90])