In [1]:
import numpy as np

Set 1:

Create a 3×3 array of all True Boolean values

Extract odd numbers from an array

Replace all odd numbers with -1

Reverse columns of a 2D array

Get indices of elements greater than 5 [hint: check where method of numpy]

Access last row - last column


In [3]:
arr1 = np.full((3, 3), True)
arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
arr2 = np.random.randint(2, 30, 15)
arr2

array([16, 12, 25,  3, 24, 24, 23, 23, 18,  7, 21,  2, 15, 25, 21],
      dtype=int32)

In [12]:
arr2[arr2%2==1]

array([25,  3, 23, 23,  7, 21, 15, 25, 21], dtype=int32)

In [13]:
arr2[arr2%2==1] = -1
arr2

array([16, 12, -1, -1, 24, 24, -1, -1, 18, -1, -1,  2, -1, -1, -1],
      dtype=int32)

In [41]:
arr3 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
arr3

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Column Reversed

In [42]:
arr3[::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [43]:
arr4 = np.random.randint(0, 10, 10)
arr4

array([7, 8, 0, 6, 8, 5, 2, 5, 6, 6], dtype=int32)

In [44]:
np.where(arr4 > 5)

(array([0, 1, 3, 4, 8, 9]),)

In [45]:
arr3[-1][-1]

np.int64(1)

Set 2:
Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

Create a 5×5 array with 1 on border and 0 inside

Create a random array of 10×10: perform stats (min, max, mean, std)

Broadcast a 1D array over a 2D array [all possible scenarios]

Sort a 2D array by column 1 [hint: check method argsort()]


In [76]:
arr4 = np.random.random((3, 4))*100
arr4 = arr4.astype(int)

In [77]:
arr4

array([[97, 77, 37, 42],
       [15,  4, 99, 37],
       [48, 85, 68, 43]])

In [78]:
arr4/100

array([[0.97, 0.77, 0.37, 0.42],
       [0.15, 0.04, 0.99, 0.37],
       [0.48, 0.85, 0.68, 0.43]])

In [180]:
arr5 = np.ones((5, 5))
arr5 = arr5.astype(int)
arr5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [181]:
arr5[1:-1,1:-1]=0
arr5

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [182]:
# arr5[0]=2
# arr5[-1]=2
# arr5[:1,1:-1]=3
# arr5[-1:,1:-1]=3
# arr5[1:-1,:1]=4
# arr5[1:-1,-1:]=4
# arr5[1:-1,1:-1]=5

In [195]:
arr6 = np.random.random((10,10))*100
arr6 = arr6.astype(int)
arr6

array([[81, 76, 88, 26,  5, 47, 49,  0, 20, 22],
       [95, 94, 48, 15, 30, 85, 19, 24, 80, 65],
       [16, 64, 81,  6,  7, 44, 95,  0, 15, 39],
       [88, 94,  2, 10, 99, 53,  6, 68, 81, 18],
       [41, 67, 63, 59, 58, 91, 58, 99, 61, 46],
       [ 7, 45, 77, 46, 82, 42, 91, 82, 66, 62],
       [56, 37, 75, 43, 14, 48, 89, 82, 73, 51],
       [ 1,  6, 42, 36, 30, 60, 66, 71,  8, 89],
       [75, 91, 99, 97, 81, 18, 73, 83, 17, 60],
       [20, 62, 49,  8, 87, 50, 75, 63, 23, 73]])

In [196]:
np.min(arr6)

np.int64(0)

In [197]:
np.max(arr6)

np.int64(99)

In [198]:
np.mean(arr6)

np.float64(52.79)

In [199]:
np.std(arr6)

np.float64(29.77727153383936)

In [206]:
arr1d = np.array([1,2,3])

In [207]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [208]:
arr2d + arr1d

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [209]:
arr2d + arr1d.reshape(3,1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [211]:
arr2d + np.array([10])

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [219]:
arr7 = np.array([[97, 77, 37, 42],
                 [15,  4, 99, 37],
                 [48, 85, 68, 43]])

In [225]:
col_ind = np.argsort(arr7[:, 0])
col_ind

array([1, 2, 0])

In [226]:
arr7[col_ind]

array([[15,  4, 99, 37],
       [48, 85, 68, 43],
       [97, 77, 37, 42]])

Set 3:

Find common elements between two arrays [with and without using intersect1d]

Subtract row mean from each row of a 2D array

Given a 4×4 array, swap the first half rows with the second half rows

Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).


In [227]:
arr10= np.array([1,2,3,6,7,5,10,2,23,3,89,25,633])
arr11 = np.array([1,2,3,18,45,20,32,100,150,200,250])

In [236]:
inter = np.intersect1d(arr10,arr11)

In [237]:
inter

array([1, 2, 3])

In [241]:
inter2 = np.isin(arr10,arr11)
arr10[inter2]

array([1, 2, 3, 2, 3])

In [242]:
arr12 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [249]:
row_mean = arr12.mean(axis=1)
row_mean = row_mean.reshape(-1, 1)
print(row_mean)
sub_mean = arr12-row_mean
sub_mean

[[2.]
 [5.]
 [8.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [250]:
arr13 = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

In [251]:
arr13[[0, 1, 2, 3]] = arr13[[2, 3, 0, 1]]
arr13

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [257]:
arr14 = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

In [258]:
arr15 = np.vstack((arr14[2:],arr14[:2]))
arr15

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [260]:
arr16 = np.random.randint(6,size=6)
arr16

array([2, 5, 3, 5, 5, 1], dtype=int32)

In [261]:
a = arr16[np.argsort(arr16)==5]
a

array([2], dtype=int32)

In [263]:
np.where(arr16 == a)[0][0]

np.int64(0)

In [264]:
idx = np.argsort(arr16)[-1]
val = arr16[idx]
print(arr16)
print("value:", val, " index", idx)

[2 5 3 5 5 1]
value: 5  index 4


In [259]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])  
unique_rows = np.unique(arr, axis=0)

print(arr)
unique_rows


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])