In [3]:
import numpy as np

In [5]:
lst = [4, 57, 83, 9, 2]

In [7]:
arr = np.array(lst)

In [9]:
lst

[4, 57, 83, 9, 2]

In [8]:
arr

array([ 4, 57, 83,  9,  2])

In [30]:
arr.shape

(5,)

In [32]:
arr.ndim

1

In [35]:
arr.dtype

dtype('int64')

In [50]:
arr1 = np.random.random(12)

In [51]:
arr1 = arr1*100

In [55]:
arr1 = arr1.astype(int)

In [57]:
arr1

array([89, 70, 44, 72, 64, 33, 91, 49, 17, 51, 95, 83])

In [66]:
arr1.shape

(12,)

In [67]:
arr1.reshape((3, 4))

array([[89, 70, 44, 72],
       [64, 33, 91, 49],
       [17, 51, 95, 83]])

In [68]:
arr1.reshape((4, 3))

array([[89, 70, 44],
       [72, 64, 33],
       [91, 49, 17],
       [51, 95, 83]])

In [69]:
arr1.reshape((6, 2))

array([[89, 70],
       [44, 72],
       [64, 33],
       [91, 49],
       [17, 51],
       [95, 83]])

In [70]:
arr1.reshape((2, 6))

array([[89, 70, 44, 72, 64, 33],
       [91, 49, 17, 51, 95, 83]])

In [72]:
arr1.reshape((1, 12))

array([[89, 70, 44, 72, 64, 33, 91, 49, 17, 51, 95, 83]])

In [74]:
arr1.shape

(12,)

In [75]:
arr1.reshape((3, 2, 2))

array([[[89, 70],
        [44, 72]],

       [[64, 33],
        [91, 49]],

       [[17, 51],
        [95, 83]]])

In [76]:
arr1.reshape((1, 3, 2, 2))

array([[[[89, 70],
         [44, 72]],

        [[64, 33],
         [91, 49]],

        [[17, 51],
         [95, 83]]]])

In [64]:
arr2 = np.random.randint(2, 10, 5)

In [65]:
arr2

array([2, 3, 7, 8, 4], dtype=int32)

In [79]:
one = np.ones((3, 4), dtype=int)

In [80]:
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [83]:
identity_m = np.identity(4, dtype=int)

In [84]:
identity_m

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [87]:
empty_a = np.empty((3, 4), dtype=int)

In [88]:
empty_a

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408]])

In [93]:
arr = np.arange(12).reshape(3, 4)

In [95]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [99]:
np.arange(12).transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
arr1 = np.arange(16).reshape(4, 4)

In [108]:
arr2 = np.arange(12).reshape(3, 4)

In [111]:
arr3 = np.arange(12).reshape(4, 3)

In [109]:
np.vstack((arr2, arr1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
np.hstack((arr1, arr3))

array([[ 0,  1,  2,  3,  0,  1,  2],
       [ 4,  5,  6,  7,  3,  4,  5],
       [ 8,  9, 10, 11,  6,  7,  8],
       [12, 13, 14, 15,  9, 10, 11]])

In [125]:
arr = np.random.randint(1, 50, 10)

In [126]:
arr

array([38, 19, 47, 34, 14,  6, 41, 39, 39, 41], dtype=int32)

In [127]:
arr.sort()

In [128]:
arr

array([ 6, 14, 19, 34, 38, 39, 39, 41, 41, 47], dtype=int32)

In [141]:
arr4 = np.random.randint(1, 50, 12).reshape(3, 4)
arr4

array([[21, 46,  3, 38],
       [ 2, 47, 19, 28],
       [23, 47, 37, 17]], dtype=int32)

In [142]:
np.sum(arr4)

np.int64(328)

In [143]:
np.sum(arr4, axis=0)

array([ 46, 140,  59,  83])

In [144]:
np.sum(arr4, axis=1)

array([108,  96, 124])

In [145]:
np.min(arr4)

np.int32(2)

In [146]:
np.min(arr4, axis=0)

array([ 2, 46,  3, 17], dtype=int32)

In [147]:
np.min(arr4, axis=1)

array([ 3,  2, 17], dtype=int32)

In [148]:
np.max(arr4)

np.int32(47)

In [149]:
np.max(arr4, axis=0)

array([23, 47, 37, 38], dtype=int32)

In [150]:
np.max(arr4, axis=1)

array([46, 47, 47], dtype=int32)

In [152]:
arr5 = np.random.randint(1, 50, 24).reshape(3, 4, 2)
arr5

array([[[11, 21],
        [34,  3],
        [ 1, 29],
        [31, 18]],

       [[13,  9],
        [48, 19],
        [17, 27],
        [35, 11]],

       [[48, 43],
        [11, 46],
        [42, 28],
        [45,  9]]], dtype=int32)

In [164]:
arr5.reshape(3, 1, 4, 2)

array([[[[11, 21],
         [34,  3],
         [ 1, 29],
         [31, 18]]],


       [[[13,  9],
         [48, 19],
         [17, 27],
         [35, 11]]],


       [[[48, 43],
         [11, 46],
         [42, 28],
         [45,  9]]]], dtype=int32)

In [157]:
np.min(arr5, axis=0)

array([[11,  9],
       [11,  3],
       [ 1, 27],
       [31,  9]], dtype=int32)

In [158]:
np.min(arr5, axis=1)

array([[ 1,  3],
       [13,  9],
       [11,  9]], dtype=int32)

In [159]:
np.min(arr5, axis=2)

array([[11,  3,  1, 18],
       [ 9, 19, 17, 11],
       [43, 11, 28,  9]], dtype=int32)

In [162]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(&quot;Original 2D array:&quot;)
print(array_2d)

# Reshape the 2D array into a 3D array with shape (3, 3, 1)
array_3d = array_2d.reshape((3, 3, 1))
# print(&quot;\nReshaped 3D array:&quot;)
print(array_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [165]:
np.min(array_3d, axis=2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
arr7 = np.random.randint(1, 20, 10)
arr7

array([15,  4,  8,  2,  8, 13,  9, 15,  1, 10], dtype=int32)

In [176]:
arr8 = np.ones((2, 1))
arr8

array([[1.],
       [1.]])

In [177]:
arr9 = np.ones((2, 2, 2))
arr9

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [178]:
arr8 + arr9

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])